import datetime
from decimal import Decimal
from typing import ClassVar, Iterator, TypeAlias, final

__version__: str

class HmrcRatesError(Exception):
    """Base class for all hmrc-rates errors."""

class UnknownCurrencyError(HmrcRatesError):
    """The currency code never appears in the requested rate series."""

class PeriodNotAvailableError(HmrcRatesError):
    """The series has no table for the requested period."""

class NotInPeriodError(HmrcRatesError):
    """The period exists but the currency is absent from it."""

class FetchError(HmrcRatesError):
    """Fetching fresh rates from HMRC failed."""

@final
class Month:
    """A calendar month, the key of HMRC monthly rate tables."""

    def __init__(self, year: int, month: int) -> None: ...
    @staticmethod
    def parse(s: str) -> Month: ...
    @staticmethod
    def from_date(date: datetime.date) -> Month: ...
    @property
    def year(self) -> int: ...
    @property
    def month(self) -> int: ...
    def next(self) -> Month: ...
    def prev(self) -> Month: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Month) -> bool: ...
    def __le__(self, other: Month) -> bool: ...
    def __gt__(self, other: Month) -> bool: ...
    def __ge__(self, other: Month) -> bool: ...
    def __hash__(self) -> int: ...

MonthLike: TypeAlias = Month | datetime.date | str
"""A month as `Month`, `datetime.date`, or a `"YYYY-MM"` string."""

Amount: TypeAlias = Decimal | int
"""An exact amount; floats are rejected because they are inexact."""

@final
class YearEnd:
    """A spot/average rate period ending 31 March or 31 December."""

    @staticmethod
    def march(year: int) -> YearEnd: ...
    @staticmethod
    def december(year: int) -> YearEnd: ...
    @staticmethod
    def from_month(month: Month) -> YearEnd | None: ...
    @property
    def year(self) -> int: ...
    @property
    def is_march(self) -> bool: ...
    def end_month(self) -> Month: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: YearEnd) -> bool: ...
    def __le__(self, other: YearEnd) -> bool: ...
    def __gt__(self, other: YearEnd) -> bool: ...
    def __ge__(self, other: YearEnd) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Currency:
    """A three-letter currency code as published by HMRC (not always ISO 4217)."""

    GBP: ClassVar[Currency]
    @property
    def code(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Currency) -> bool: ...
    def __le__(self, other: Currency) -> bool: ...
    def __gt__(self, other: Currency) -> bool: ...
    def __ge__(self, other: Currency) -> bool: ...
    def __hash__(self) -> int: ...

@final
class RateType:
    """The four rate series HMRC has published."""

    MONTHLY: ClassVar[RateType]
    SPOT: ClassVar[RateType]
    AVERAGE: ClassVar[RateType]
    WEEKLY: ClassVar[RateType]
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Period:
    """The period a rate or table applies to."""

    @property
    def kind(self) -> str:
        """``"month"``, ``"year_end"`` or ``"week"``."""

    @property
    def month(self) -> Month | None: ...
    @property
    def year_end(self) -> YearEnd | None: ...
    @property
    def start(self) -> datetime.date | None: ...
    @property
    def end(self) -> datetime.date | None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Rate:
    """A resolved rate: currency units per £1, exact decimal arithmetic."""

    @property
    def units_per_gbp(self) -> Decimal: ...
    @property
    def currency(self) -> Currency: ...
    @property
    def period(self) -> Period: ...
    def to_gbp(self, amount: Amount) -> Decimal: ...
    def from_gbp(self, gbp: Amount) -> Decimal: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Table:
    """One period's rates."""

    @property
    def period(self) -> Period: ...
    @property
    def rate_type(self) -> RateType: ...
    def rate(self, code: str) -> Rate: ...
    def get(self, code: str) -> Rate | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[Currency, Rate]]: ...

@final
class Rates:
    """All bundled HMRC rate tables. Constructing is free."""

    def __init__(self) -> None: ...
    def monthly_rate(self, code: str, month: MonthLike) -> Rate: ...
    def monthly_rate_or_earlier(
        self, code: str, month: MonthLike, max_months_back: int
    ) -> Rate: ...
    def monthly(self, month: MonthLike) -> Table: ...
    def spot(self, period: YearEnd) -> Table: ...
    def average(self, period: YearEnd) -> Table: ...
    def weekly(self, date: datetime.date) -> Table: ...
    def months(self) -> list[Month]: ...
    def spot_periods(self) -> list[YearEnd]: ...
    def average_periods(self) -> list[YearEnd]: ...
    def weeks(self) -> list[Period]: ...
    def currencies(self, table: RateType) -> list[Currency]: ...

@final
class Updater:
    """Fetches newly published rates, caching files on disk."""

    def __init__(
        self, *, cache_dir: str | None = None, base_url: str | None = None
    ) -> None: ...
    def cached(self) -> Rates: ...
    def refreshed(self) -> Rates: ...
